options:
  docker: true

pipelines:
  default:
    - step:
        deployment: production
        script:
          - export IMAGE_NAME=thilinaperera/nginx-php-server:latest
          - docker build -t $IMAGE_NAME .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME